# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'panel_v3.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import ClassesReqByAlgorithm as backend


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(710, 554)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.sppiwnica = QtWidgets.QSpinBox(self.centralwidget)
        self.sppiwnica.setGeometry(QtCore.QRect(200, 230, 141, 22))
        self.sppiwnica.setMaximum(9999)
        self.sppiwnica.setSingleStep(10)
        self.sppiwnica.setObjectName("sppiwnica")
        self.spdach = QtWidgets.QSpinBox(self.centralwidget)
        self.spdach.setGeometry(QtCore.QRect(200, 210, 141, 22))
        self.spdach.setMaximum(9999)
        self.spdach.setSingleStep(10)
        self.spdach.setObjectName("spdach")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 70, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 100, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 120, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.spZd = QtWidgets.QSpinBox(self.centralwidget)
        self.spZd.setGeometry(QtCore.QRect(200, 100, 141, 22))
        self.spZd.setMaximum(9999)
        self.spZd.setSingleStep(10)
        self.spZd.setObjectName("spZd")
        self.spZn = QtWidgets.QSpinBox(self.centralwidget)
        self.spZn.setGeometry(QtCore.QRect(200, 120, 141, 22))
        self.spZn.setMaximum(9999)
        self.spZn.setSingleStep(10)
        self.spZn.setObjectName("spZn")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(20, 140, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(40, 180, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(20, 210, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(20, 230, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(40, 260, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(20, 300, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.spb = QtWidgets.QSpinBox(self.centralwidget)
        self.spb.setGeometry(QtCore.QRect(200, 300, 141, 22))
        self.spb.setMaximum(9999999)
        self.spb.setSingleStep(10000)
        self.spb.setObjectName("spb")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(20, 330, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setEnabled(True)
        self.tableWidget.setGeometry(QtCore.QRect(480, 100, 211, 131))
        self.tableWidget.setSizeIncrement(QtCore.QSize(2, 5))
        self.tableWidget.setStatusTip("")
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setRowCount(4)
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(40, 10, 301, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(480, 10, 301, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(480, 70, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(480, 260, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 430, 681, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_3.setGeometry(QtCore.QRect(480, 290, 211, 101))
        self.tableWidget_3.setSizeIncrement(QtCore.QSize(2, 5))
        self.tableWidget_3.setRowCount(3)
        self.tableWidget_3.setColumnCount(2)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.horizontalHeader().setVisible(False)
        self.tableWidget_3.verticalHeader().setVisible(False)
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(20, 380, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(160, 380, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.doubleSpinBox.setGeometry(QtCore.QRect(200, 140, 141, 21))
        self.doubleSpinBox.setMaximum(1.0)
        self.doubleSpinBox.setSingleStep(0.01)
        self.doubleSpinBox.setProperty("value", 0.0)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 710, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "Zużycie prądu [kWh]"))
        self.label_5.setText(_translate("MainWindow", "Dzień:"))
        self.label_6.setText(_translate("MainWindow", "Noc:"))
        self.label_7.setText(_translate("MainWindow", "Cena prądu [PLN/kWh] :"))
        self.label_8.setText(_translate("MainWindow", "Dostępna powierzchnia [m2]"))
        self.label_9.setText(_translate("MainWindow", "Dach:"))
        self.label_10.setText(_translate("MainWindow", "Piwnica:"))
        self.label_11.setText(_translate("MainWindow", "Twoja inwestycja:"))
        self.label_12.setText(_translate("MainWindow", "Budżet [PLN]:"))
        self.checkBox.setText(_translate("MainWindow", "Nie korzystaj z baterii"))
        self.label_13.setText(_translate("MainWindow", "Parametry inwestycji:"))
        self.label_14.setText(_translate("MainWindow", "Wynik:"))
        self.label_15.setText(_translate("MainWindow", "Panele:"))
        self.label_16.setText(_translate("MainWindow", "Baterie:"))
        self.pushButton.setText(_translate("MainWindow", "START"))
        self.label_17.setText(_translate("MainWindow", "Zysk po 20 latach:"))
        self.label.setText(_translate("MainWindow", "Naciśnij START"))
        self.pushButton.clicked.connect(self.startalg)

    def startalg(self):
        budget = self.spb.value()
        Zd = self.spZd.value() * 1000
        Zn = self.spZn.value() * 1000
        cp = self.doubleSpinBox.value() / 1000
        apmax = self.spdach.value()
        abmax = self.sppiwnica.value()

        # inicjalizacja typow paneli
        p1 = backend.Pv(11, 4900, 3100, 0.4, 1.5)  # cena jest druga
        p2 = backend.Pv(12, 7000, 3100, 0.5, 1.5)  # def __init__(self, id, price, power, efficiency, area, quantity=0):
        p3 = backend.Pv(13, 1680, 3100, 0.2, 1.5)
        p4 = backend.Pv(14, 7000, 3100, 0.3, 1.5)
        # inicjalizacja typow akumulatorow
        b1 = backend.Battery(21, 20000, 10000, 0.85,
                             1)  # def __init__(self, id, price, capacity, efficiency, area, quantity=0):
        b2 = backend.Battery(22, 18000, 7000, 0.85, 1)
        b3 = backend.Battery(23, 19200, 12000, 0.85, 1)

        Pvs = [p1, p2, p3, p4]

        if self.checkBox.isChecked():
            batteries = []
        else:
            batteries = [b1, b2, b3]

        alg = backend.ForbiddenAlgorithm(Pvs[:], batteries[:], budget, abmax, apmax)
        alg.Zd = Zd
        alg.Zn = Zn
        alg.cp = cp

        solution = alg.find_min_v2()

        #        print("Max value ->", solution[0], "\n")
        #        for p in solution[1]:
        #            print(p)
        #
        #        for b in solution[2]:
        #            print(b)
        #
        row = 0
        for battery in solution[1]:
            self.tableWidget.setItem(row, 0, QtWidgets.QTableWidgetItem(str(battery.id)))
            self.tableWidget.setItem(row, 1, QtWidgets.QTableWidgetItem(str(battery.quantity)))
            row += 1

        row = 0
        for pv in solution[2]:
            self.tableWidget_3.setItem(row, 0, QtWidgets.QTableWidgetItem(str(pv.id)))
            self.tableWidget_3.setItem(row, 1, QtWidgets.QTableWidgetItem(str(pv.quantity)))
            row += 1

        # self.tableWidget.setItem(1,1, QtWidgets.QTableWidgetItem("test11"))
        self.tableWidget.show()

        result_msg = "{:,} zł"
        self.label.setText(result_msg.format(round(solution[0])))
        print(str(solution[0]))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
